### ISSUE TITLE
PM time bug with sc_event_date_time

### ISSUE THREAD

**Issue by jmswrnr** [pippinsplugins/Sugar-Event-Calendar-Lite#8]
A slight bug in **includes/meta-boxes.php** on line [145-148](https://github.com/pippinsplugins/Sugar-Event-Calendar-Lite/blob/master/includes/meta-boxes.php#L145)

It ignores PM times when setting the ```sc_event_date_time``` meta value.

```php
	if( $am_pm == 'pm' && $hour < 12 )
		$hour += 12;
	elseif( $am_pm == 'am' && $hour >= 12 )
		$hour -= 12;

// $hour should be $hours

	if( $am_pm == 'pm' && $hours < 12 )
		$hours += 12;
	elseif( $am_pm == 'am' && $hours >= 12 )
		$hours -= 12;
```

**Comment by pippinsplugins** [comment]
Going out in 1.0.5 today.

**Comment by kcpt-steven-kohlmeyer** [comment]
Muchas Gracias!
